In order to make our MD files synced with having the fix by default
murex/mikado-testbuilders-kata pull request #50
Opened 2021-02-02 17:18 UTC by aatwi

1. Add a section for the live coding in the Building_Test_Data MD file 
2. Fill in the TODO sections of the Mikado_Method MD file 
3. Add new screenshots from the youtube videos 
4. Fix some text and typos in the files

2021-02-03 13:26 UTC, mengdaming approved these changes

2021-02-03 14:50 UTC, philou requested changes
A few cut and paste issues

2021-02-03 14:50 UTC, philou commented on docs/3_Building_Test_Data.md
> +### Use Mikado Method to setup data for a test on Invoice
Shouldn't it be 'Test Data Builders' instead of Mikado method here?

2021-02-03 14:50 UTC, philou commented on docs/3_Building_Test_Data.md
> +Make sure your project keeps building all the time. Notice every time you have something useful.
I think we should not put this ~~'Make sure your project keeps building all the time'~~ Letting them go through code that does not build highlights a shortcoming of test data builders when used alone

2021-02-03 14:50 UTC, philou commented on docs/3_Building_Test_Data.md
> +### Use Mikado Method to setup data for a test on Report Generator (advanced)
Again: Test Data Builders instead of Mikado Method

2021-02-03 17:24 UTC, aatwi commented
@philou I updated the text as suggested

2021-02-04 08:35 UTC, philou approved these changes

2021-02-04 08:35 UTC, merged